---
name: Continous Integration

on:
  pull_request:
    branches:
      - trunk

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Format check
      run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-latest
    needs: [format-check]
    steps:
    - uses: actions/checkout@main
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Lint check
      run: cargo clippy -- -W clippy::pedantic

  run-examples:
    runs-on: ubuntu-latest
    needs: [format-check]
    steps:
    - uses: actions/checkout@main
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Test Check Health
      run: cargo run --example check-health

  run-tests:
    runs-on: ubuntu-latest
    needs: [format-check]
    steps:
    - uses: actions/checkout@main
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Test
      run: cargo test